# Default to Local setup (connecting to Docker Compose from host)
kafka.bootstrap.servers=localhost:9092
schema.registry.url=http://localhost:8081

# Quarkus Kafka extension config
quarkus.http.cors=true
quarkus.http.cors.origins=/.*/
quarkus.http.cors.headers=accept, authorization, content-type, x-requested-with
quarkus.http.cors.methods=GET, OPTIONS, POST, PUT, DELETE
mp.messaging.connector.smallrye-kafka.apicurio.registry.url=${schema.registry.url}
mp.messaging.connector.smallrye-kafka.schema.registry.url=${schema.registry.url}

# PostgreSQL Database config (Local)
quarkus.datasource.db-kind=postgresql
quarkus.datasource.jdbc.url=jdbc:postgresql://localhost:5432/streamingdb
quarkus.datasource.username=user
quarkus.datasource.password=password

# Hibernate ORM configuration
quarkus.hibernate-orm.database.generation=update
quarkus.hibernate-orm.log.sql=false

# Kafka Producer Configs (Outgoing)
mp.messaging.outgoing.user-events.topic=user-events
mp.messaging.outgoing.user-events.key.serializer=org.apache.kafka.common.serialization.StringSerializer
mp.messaging.outgoing.user-events.value.serializer=io.confluent.kafka.serializers.KafkaAvroSerializer
mp.messaging.outgoing.user-events.merge=true

mp.messaging.outgoing.login-events.topic=login-events
mp.messaging.outgoing.login-events.key.serializer=org.apache.kafka.common.serialization.StringSerializer
mp.messaging.outgoing.login-events.value.serializer=io.confluent.kafka.serializers.KafkaAvroSerializer
mp.messaging.outgoing.login-events.merge=true

mp.messaging.outgoing.department-events.topic=department-events
mp.messaging.outgoing.department-events.key.serializer=org.apache.kafka.common.serialization.StringSerializer
mp.messaging.outgoing.department-events.value.serializer=io.confluent.kafka.serializers.KafkaAvroSerializer
mp.messaging.outgoing.department-events.merge=true

mp.messaging.outgoing.country-risk-events.topic=country-risk-events
mp.messaging.outgoing.country-risk-events.key.serializer=org.apache.kafka.common.serialization.StringSerializer
mp.messaging.outgoing.country-risk-events.value.serializer=io.confluent.kafka.serializers.KafkaAvroSerializer
mp.messaging.outgoing.country-risk-events.merge=true

# Kafka Streams App Configuration
quarkus.kafka-streams.bootstrap-servers=${kafka.bootstrap.servers}
quarkus.kafka-streams.application-id=fraud-detector-app
quarkus.kafka-streams.topics=login-events

# Docker Dev Profile (Inside the Docker Compose network)
%docker.kafka.bootstrap.servers=broker:29092
%docker.schema.registry.url=http://schema-registry:8081
%docker.quarkus.datasource.jdbc.url=jdbc:postgresql://postgres:5432/streamingdb
